modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Steveaaaaa/Ability/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Steveaaaaa/Ability"
authors="Steveaaaaa"
description='''
A data-driven RPG skill and ability mod for Minecraft.
'''

[[mixins]]
config="ability.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="player_animation_library"
type="required"
versionRange="[1.1.5,)"
ordering="AFTER"
side="BOTH"
